/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'customerName' : string,
  'status' : BookingStatus,
  'destination' : string,
  'cargoType' : string,
  'owner' : Principal,
  'origin' : string,
  'assignedDriver' : [] | [bigint],
  'passengers' : bigint,
  'notes' : [] | [string],
  'phone' : string,
  'dateTime' : Time,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null } |
  { 'inProgress' : null };
export interface Driver {
  'id' : bigint,
  'vehicleType' : string,
  'licensePlate' : string,
  'name' : string,
  'available' : boolean,
  'phone' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDriver' : ActorMethod<[string, string, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignDriver' : ActorMethod<[bigint, bigint], undefined>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'createBooking' : ActorMethod<
    [string, string, string, string, Time, bigint, string, [] | [string]],
    bigint
  >,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllDrivers' : ActorMethod<[], Array<Driver>>,
  'getBookingById' : ActorMethod<[bigint], Booking>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeDriver' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'updateDriverAvailability' : ActorMethod<[bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];